'use client';
import { useMemo, useState } from 'react';
import Header from '@/components/domera/Header';
import Footer from '@/components/domera/Footer';
import ProductCard from '@/components/domera/ProductCard';
import Seo from '@/components/Seo';
import { ArrowLeft, ArrowRight, Sparkles } from 'lucide-react';
import { track } from '@/lib/analytics';

const steps = [
  { key:'size', q:'Яке спальне місце вам потрібне?', options:[['140×200','140×200'],['160×200','160×200'],['180×200','180×200'],['200×200','200×200']] },
  { key:'budget', q:'Який бюджет на ліжко?', options:[[12000,'до 12 000 ₴'],[16000,'до 16 000 ₴'],[22000,'до 22 000 ₴'],[999999,'Без обмежень']] },
  { key:'mechanism', q:'Потрібен підйомний механізм?', options:[['yes','Так, потрібне місце для зберігання'],['no','Ні, стандартна основа'],['any','Не принципово']] },
  { key:'style', q:'Яке відчуття має створювати спальня?', options:[['soft','Мʼяка та світла'],['minimal','Архітектурний мінімалізм'],['premium','Глибокий преміальний образ'],['any','Покажіть найкраще']] },
];

export default function BedFinder() {
  const [step,setStep]=useState(0); const [answers,setAnswers]=useState({}); const [products,setProducts]=useState([]); const [done,setDone]=useState(false); const [loading,setLoading]=useState(false);
  const choose=async(v)=>{ const next={...answers,[steps[step].key]:v}; setAnswers(next); track('bed_finder_step',{step:step+1,answer:String(v)}); if(step<steps.length-1){setStep(step+1);return;} setLoading(true); try{const res=await fetch('/data/homefort-beds.json',{cache:'no-store'}); const data=await res.json(); let list=data.products||data.items||[]; list=list.filter(p=>Number(p.price||0)<=Number(next.budget||999999)); if(next.size) list=list.filter(p=>(p.sizes||[]).some(s=>String(s).replace(/см/gi,'').replace(/[xх]/gi,'×').includes(next.size))); const scored=list.map(p=>{const t=`${p.name} ${p.shortDescription||''}`.toLowerCase(); let score=0; if(next.style==='soft' && /soft|sunny|adele|maria/.test(t))score+=3; if(next.style==='minimal' && /seul|lider|drim/.test(t))score+=3; if(next.style==='premium' && /lux|bestseller|elena/.test(t))score+=3; if(p.salePercent>0)score+=1; return {...p,_score:score};}).sort((a,b)=>b._score-a._score||a.price-b.price); setProducts(scored.slice(0,3)); track('bed_finder_complete',{recommended:scored.slice(0,3).map(p=>p.sku)});}catch{setProducts([]);} setLoading(false);setDone(true);};
  const progress=done?100:(step/steps.length)*100;
  return <div className="min-h-screen bg-milk"><Seo title="Підібрати ліжко за 60 секунд — DOMERA" description="Smart Finder DOMERA підбере 3 моделі ліжок за розміром, бюджетом і стилем." canonical="/bed-finder"/><Header/><main className="pt-[78px]"><div className="mx-auto max-w-[1100px] px-6 lg:px-12 py-12 md:py-20"><div className="flex items-center gap-2 text-champagne mb-3"><Sparkles className="w-4 h-4"/><span className="text-[10px] tracking-[0.24em] uppercase">DOMERA SMART FINDER</span></div><h1 className="font-heading text-[clamp(2.5rem,6vw,4.6rem)] text-espresso leading-[.98]">Знайдемо ваше ліжко<br/>за 60 секунд</h1><p className="mt-5 text-mocha max-w-xl">Чотири питання — і ми покажемо три моделі, які найбільше відповідають вашій спальні та бюджету.</p><div className="mt-10 h-px bg-espresso/10"><div className="h-px bg-espresso transition-all" style={{width:`${progress}%`}}/></div>{!done ? <div className="mt-12">{loading?<p className="text-mocha">Підбираємо моделі…</p>:<><p className="text-[10px] tracking-[0.22em] uppercase text-champagne">Питання {step+1} / {steps.length}</p><h2 className="font-heading text-3xl md:text-4xl text-espresso mt-3 mb-7">{steps[step].q}</h2><div className="grid sm:grid-cols-2 gap-3">{steps[step].options.map(([v,l])=><button key={String(v)} onClick={()=>choose(v)} className="group text-left border border-espresso/15 hover:border-espresso p-5 md:p-6 transition-colors"><span className="font-heading text-xl text-espresso">{l}</span><ArrowRight className="w-4 h-4 text-mocha mt-4 group-hover:translate-x-1 transition-transform"/></button>)}</div>{step>0&&<button onClick={()=>setStep(step-1)} className="mt-7 inline-flex items-center gap-2 text-sm text-mocha"><ArrowLeft className="w-4 h-4"/>Назад</button>}</>}</div>:<div className="mt-12"><p className="text-[10px] tracking-[0.22em] uppercase text-champagne">Ваш shortlist</p><h2 className="font-heading text-4xl text-espresso mt-2">3 моделі для вас</h2>{products.length?<div className="mt-8 grid md:grid-cols-3 gap-7">{products.map(p=><ProductCard key={p.id||p.slug} product={p}/>)}</div>:<p className="mt-6 text-mocha">Не знайшли точного збігу. Спробуйте інший бюджет або розмір.</p>}<button onClick={()=>{setDone(false);setStep(0);setAnswers({});}} className="mt-10 px-6 py-3 border border-espresso/20 text-[11px] uppercase tracking-[0.18em] text-espresso">Пройти ще раз</button></div>}</div></main><Footer/></div>;
}