// Local entity schemas for the admin panel (the installed SDK has no schema() method).
// Mirrors base44/entities/*.jsonc — only editable fields (built-ins id/created_date/updated_date/created_by_id excluded).

const str = (title) => ({ type: 'string', title });
const num = (title) => ({ type: 'number', title });
const bool = (title) => ({ type: 'boolean', title });
const en = (title, values, def) => ({ type: 'string', title, enum: values, ...(def ? { default: def } : {}) });
const arrStr = (title) => ({ type: 'array', items: { type: 'string' }, title });
const date = (title) => ({ type: 'string', format: 'date', title });
const dateTime = (title) => ({ type: 'string', format: 'date-time', title });

export const ENTITY_SCHEMAS = {
  Product: {
    required: ['name', 'slug', 'category', 'price'],
    properties: {
      name: str('Назва'),
      slug: str('Slug'),
      sku: str('Артикул'),
      category: en('Категорія', ['beds', 'mattresses', 'toppers', 'pillows', 'duvets', 'bedding', 'kids-mattresses']),
      subcategory: str('Підкатегорія'),
      shortDescription: str('Короткий опис'),
      fullDescription: str('Повний опис'),
      price: num('Ціна'),
      oldPrice: num('Стара ціна'),
      salePercent: num('Знижка %'),
      availability: en('Наявність', ['in_stock', 'made_to_order', 'out_of_stock'], 'made_to_order'),
      productionTime: str('Термін виготовлення'),
      images: arrStr('Зображення'),
      videoUrl: str('Відео URL'),
      colors: arrStr('Кольори (hex)'),
      fabrics: arrStr('Тканини'),
      sizes: arrStr('Розміри'),
      material: str('Матеріал'),
      liftingMechanism: bool('Підйомний механізм'),
      dimensions: str('Габарити'),
      height: str('Висота'),
      weight: str('Вага'),
      sleepingWidth: str('Ширина спального місця'),
      sleepingLength: str('Довжина спального місця'),
      externalWidth: str('Зовнішня ширина'),
      externalLength: str('Зовнішня довжина'),
      headboardHeight: str('Висота спинки'),
      bedHeight: str('Висота ліжка'),
      clearanceFromFloor: str('Кліренс від підлоги'),
      technicalDrawing: str('Технічне креслення'),
      hardness: str('Жорсткість'),
      springType: str('Тип пружин'),
      loadPerSleeper: str('Навантаження на спальне місце'),
      coverMaterial: str('Матеріал чохла'),
      coverRemovable: bool('Знімний чохол'),
      frameMaterial: str('Матеріал каркаса'),
      foamType: str('Тип піни'),
      foamDensity: str('Щільність піни'),
      hardware: str('Фурнітура'),
      fabricComposition: str('Склад тканини'),
      fabricDurability: str('Зносостійкість тканини'),
      mechanismManufacturer: str('Виробник механізму'),
      legsMaterial: str('Матеріал ніжок'),
      certifications: str('Сертифікація'),
      specifications: { type: 'array', items: { type: 'object', properties: { label: { type: 'string' }, value: { type: 'string' } } }, title: 'Додаткові характеристики' },
      warranty: str('Гарантія'),
      rating: num('Рейтинг'),
      reviewsCount: num('К-сть відгуків'),
      featured: bool('Бестселер'),
      seoTitle: str('SEO Title'),
      seoDescription: str('SEO Description'),
      seoH1: str('SEO H1'),
      canonicalUrl: str('Canonical URL'),
      indexable: bool('Індексувати'),
      ogTitle: str('OG Title'),
      ogDescription: str('OG Description'),
      ogImage: str('OG Image'),
      imageAlt: str('Alt зображення'),
    },
  },
  ProductVariant: {
    required: ['productId', 'variantSKU'],
    properties: {
      productId: str('Product ID'),
      variantSKU: str('Variant SKU'),
      size: str('Розмір'),
      fabricId: str('Тканина ID'),
      color: str('Колір'),
      headboard: str('Спинка'),
      mechanism: en('Механізм', ['none', 'lifting'], 'none'),
      priceAdjustment: num('Коригування ціни'),
      finalPrice: num('Фінальна ціна'),
      oldPrice: num('Стара ціна'),
      availability: en('Наявність', ['in_stock', 'made_to_order', 'out_of_stock'], 'made_to_order'),
      productionTime: str('Термін виготовлення'),
      images: arrStr('Зображення'),
      active: bool('Активний'),
    },
  },
  Category: {
    required: ['key', 'name'],
    properties: {
      key: str('Ключ (Product.category)'),
      name: str('Назва'),
      h1: str('H1'),
      seoTitle: str('SEO Title'),
      seoDescription: str('Meta Description'),
      seoIntro: str('SEO Intro'),
      canonicalUrl: str('Canonical URL'),
      image: str('Зображення'),
      imageAlt: str('Alt зображення'),
      ogTitle: str('OG Title'),
      ogDescription: str('OG Description'),
      ogImage: str('OG Image'),
      indexable: bool('Індексувати'),
      faq: { type: 'array', items: { type: 'object', properties: { q: { type: 'string' }, a: { type: 'string' } } }, title: 'FAQ' },
      order: num('Порядок'),
    },
  },
  Fabric: {
    required: ['name', 'slug'],
    properties: {
      name: str('Назва'),
      slug: str('Slug'),
      category: en('Категорія', ['upholstery', 'bedding', 'curtain', 'decor'], 'upholstery'),
      composition: str('Склад'),
      martindale: num('Martindale (цикли)'),
      macroImage: str('Макро-зображення'),
      swatchImage: str('Зразок (swatch)'),
      colorHex: str('Колір (hex)'),
      priceModifier: num('Коригування ціни'),
      description: str('Опис'),
      active: bool('Активна'),
    },
  },
  Bundle: {
    required: ['name', 'slug'],
    properties: {
      name: str('Назва'),
      slug: str('Slug'),
      tier: en('Тір', ['base', 'comfort', 'complete'], 'base'),
      description: str('Опис'),
      image: str('Зображення'),
      products: { type: 'array', items: { type: 'object', properties: { productId: { type: 'string' }, qty: { type: 'number', default: 1 } } }, title: 'Товари' },
      discountType: en('Тип знижки', ['percent', 'fixed'], 'percent'),
      discountValue: num('Значення знижки'),
      active: bool('Активний'),
      startDate: dateTime('Дата початку'),
      endDate: dateTime('Дата завершення'),
    },
  },
};

export function getSchema(name) {
  return ENTITY_SCHEMAS[name] || { required: [], properties: {} };
}